### ISSUE TITLE
Nvidia API 504 Error

### ISSUE THREAD

**Issue by KCHopkins** [samuelm2/Nvidia-Notify#18]
"Connection failed...
                HTTPSConnectionPool(host='api-prod.nvidia.com', port=443): Read timed out. (read timeout=5)"

**Comment by Kosyne** [comment]
![image](https://user-images.githubusercontent.com/356616/94496570-5bc34200-01ba-11eb-9a96-a0778b19708c.png)

I'm seeing the same on my end. Looks like the NVIDIA API is down right now. Nothing we can do on our end, gotta wait for NVIDIA to fix their stuff.

**Comment by KCHopkins** [comment]
If it stays down indefinitely would a local copy of the API listing work the same? It was posted in a previous issue post. If that was put in a json file could that substitute the API call? (Sorry if this doesn’t make sense I’m fairly new to coding)

**Comment by Kosyne** [comment]
Are you referring to following the instructions here: https://github.com/samuelm2/Nvidia-Notify/wiki/Getting-NVIDIA-API-URL ?

The issue is the API is down on NVIDIA's end, so there's nothing we can do. However, if you notice that you still get a proper '200' response to the 'api-prod' request in your own testing, you can absolutely use that link you find instead. (If such a theoretical case were to happen, it would mean that they changed the API URL).
